[workspace]
members = ["prmi", "prmi-sys"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.96"
license = "MIT"
repository = "https://github.com/fg-labs/prmi"
authors = ["Fulcrum Genomics LLC"]

[workspace.dependencies]
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
memmap2 = "0.9"
byteorder = "1.5"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
rayon = "1.10"
noodles-fasta = "0.61"
libsais = { version = "0.2", features = ["openmp"] }
indicatif = "0.17"
approx = "0.5"
sha2 = "0.10"
hex = "0.4"
time = { version = "0.3", default-features = false, features = ["formatting", "macros", "std"] }
anyhow = "1"
libc = "0.2"

[profile.release]
debug = true
lto = "thin"
codegen-units = 1
