// Copyright (C) 2026 Fulcrum Genomics LLC
// SPDX-License-Identifier: MIT

//! C FFI shim for prmi. See `include/prmi.h` (generated by build.rs).

#![allow(non_camel_case_types)]

mod errors;
mod handle;

use crate::errors::{clear_last_error, set_last_error, with_last_error};
use crate::handle::{prmi_index_t, Handle};
use libc::size_t;
use prmi::index::LearnedIndex;
use std::ffi::CStr;
use std::os::raw::{c_char, c_int};
use std::path::Path;

/// Open a sidecar by prefix; expects <prefix>.{meta,sa,l1,l2}.
///
/// Returns 0 on success and writes the handle to *out_handle.
/// Returns negative on error; *out_handle is set to NULL.
///
/// # Safety
/// `sidecar_prefix` must be a valid NUL-terminated C string. `out_handle`
/// must be a valid writable pointer.
#[no_mangle]
pub unsafe extern "C" fn prmi_open(
    sidecar_prefix: *const c_char,
    out_handle: *mut *mut prmi_index_t,
) -> c_int {
    clear_last_error();
    if sidecar_prefix.is_null() || out_handle.is_null() {
        set_last_error("prmi_open: null pointer argument");
        return -1;
    }
    let cstr = unsafe { CStr::from_ptr(sidecar_prefix) };
    let s = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => {
            set_last_error("prmi_open: prefix is not valid UTF-8");
            unsafe { *out_handle = std::ptr::null_mut() };
            return -2;
        }
    };
    match LearnedIndex::open(Path::new(s)) {
        Ok(idx) => {
            unsafe { *out_handle = Handle(idx).into_raw() };
            0
        }
        Err(e) => {
            set_last_error(&format!("{e}"));
            unsafe { *out_handle = std::ptr::null_mut() };
            -3
        }
    }
}

/// Release all resources held by the handle. Safe to call with NULL.
///
/// # Safety
/// `handle` must be NULL or have been returned by `prmi_open` and not yet
/// closed.
#[no_mangle]
pub unsafe extern "C" fn prmi_close(handle: *mut prmi_index_t) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Handle::from_raw(handle) });
}

/// Thread-local last-error string. Valid until the next prmi_* call on
/// the same thread. Never returns NULL — empty string if no error.
#[no_mangle]
pub extern "C" fn prmi_last_error_message() -> *const c_char {
    with_last_error(|c| c.as_ptr())
}

/// Predict the SA position for a 32-mer key.
///
/// Returns 0 on success; negative on error. Writes the predicted SA position
/// and the error bound to the out-pointers.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`. Both out-pointers must
/// be valid writable u64 locations.
#[no_mangle]
pub unsafe extern "C" fn prmi_lookup(
    handle: *const prmi_index_t,
    key: u64,
    out_predicted_sa_pos: *mut u64,
    out_err: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || out_predicted_sa_pos.is_null() || out_err.is_null() {
        set_last_error("prmi_lookup: null pointer argument");
        return -1;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let (pos, err) = h.0.lookup(key);
    unsafe {
        *out_predicted_sa_pos = pos;
        *out_err = err;
    }
    0
}

/// Resolve an SA range matching the query against the caller-owned pac.
///
/// `pac` is a 2-bit-coded reference at **1 base per byte** (values 0..=3).
/// `pac_len` is its length in bytes — explicit to avoid silent overruns
/// (the brief §5 omits the length; we add it as an authorized deviation).
///
/// Returns 0 on match (l > 0), 1 if no match (l == 0), negative on error.
///
/// # Safety
/// All pointers must be valid. `query` and `pac` must point to slices of
/// length `query_len` and `pac_len` respectively. Out-pointers must be
/// valid writable u64 locations.
#[no_mangle]
pub unsafe extern "C" fn prmi_smem_range(
    handle: *const prmi_index_t,
    query: *const u8,
    query_len: c_int,
    pac: *const u8,
    pac_len: size_t,
    out_k: *mut u64,
    out_l: *mut u64,
    out_s: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null()
        || query.is_null()
        || pac.is_null()
        || out_k.is_null()
        || out_l.is_null()
        || out_s.is_null()
    {
        set_last_error("prmi_smem_range: null pointer argument");
        return -1;
    }
    if query_len < 0 {
        set_last_error("prmi_smem_range: negative query_len");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let q = unsafe { std::slice::from_raw_parts(query, query_len as usize) };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_len) };

    match h.0.smem_range(q, pac_slice) {
        Ok((k, l, s)) => {
            unsafe {
                *out_k = k;
                *out_l = l;
                *out_s = s;
            }
            if l == 0 {
                1
            } else {
                0
            }
        }
        Err(e) => {
            set_last_error(&format!("{e}"));
            -3
        }
    }
}

/// Number of SA entries in the loaded sidecar.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`, or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn prmi_sa_num(handle: *const prmi_index_t) -> size_t {
    if handle.is_null() {
        return 0;
    }
    unsafe { Handle::as_ref(handle) }.0.sa_num() as size_t
}

/// Global max prediction error stored in the sidecar.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`, or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn prmi_max_error_bound(handle: *const prmi_index_t) -> u64 {
    if handle.is_null() {
        return 0;
    }
    unsafe { Handle::as_ref(handle) }.0.max_error_bound()
}

/// Format version string — always "PRMIv1" for v0.1. Always non-NULL.
///
/// # Safety
/// `handle` may be NULL; the returned pointer is a static C string and
/// remains valid for the lifetime of the process.
#[no_mangle]
pub unsafe extern "C" fn prmi_format_version(handle: *const prmi_index_t) -> *const c_char {
    static CSTR: &[u8] = b"PRMIv1\0";
    let _ = handle;
    CSTR.as_ptr() as *const c_char
}
