// Copyright (C) 2026 Fulcrum Genomics LLC
// SPDX-License-Identifier: MIT

//! C FFI shim for prmi. See `include/prmi.h` (generated by build.rs).

#![allow(non_camel_case_types)]
#![warn(missing_docs)]

mod errors;
mod handle;

use crate::errors::{clear_last_error, set_last_error, with_last_error};
use crate::handle::{prmi_index_t, Handle};
use libc::size_t;
use prmi::index::LearnedIndex;
use std::ffi::CStr;
use std::os::raw::{c_char, c_int};
use std::path::Path;

/// Packed-pac byte length (`ceil(num_bases / 4)`) as `usize`, or `None` if the
/// value does not fit `usize` (only possible on narrow-`usize` targets). Guards
/// the u64→usize narrowing before a packed-pac slice is constructed.
#[inline]
fn packed_pac_bytes(pac_num_bases: u64) -> Option<usize> {
    usize::try_from(pac_num_bases.div_ceil(4)).ok()
}

/// Open a sidecar by prefix; expects `<prefix>.{meta,sa,l1,l2}`.
///
/// Returns 0 on success and writes the handle to *out_handle.
/// Returns negative on error; *out_handle is set to NULL.
///
/// # Safety
/// `sidecar_prefix` must be a valid NUL-terminated C string. `out_handle`
/// must be a valid writable pointer.
#[no_mangle]
pub unsafe extern "C" fn prmi_open(
    sidecar_prefix: *const c_char,
    out_handle: *mut *mut prmi_index_t,
) -> c_int {
    clear_last_error();
    if sidecar_prefix.is_null() || out_handle.is_null() {
        set_last_error("prmi_open: null pointer argument");
        // Clear any stale handle the caller is reusing (only when out_handle
        // itself is non-null and thus safe to write through).
        if !out_handle.is_null() {
            unsafe { *out_handle = std::ptr::null_mut() };
        }
        return -1;
    }
    let cstr = unsafe { CStr::from_ptr(sidecar_prefix) };
    let s = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => {
            set_last_error("prmi_open: prefix is not valid UTF-8");
            unsafe { *out_handle = std::ptr::null_mut() };
            return -2;
        }
    };
    match LearnedIndex::open(Path::new(s)) {
        Ok(idx) => {
            unsafe { *out_handle = Handle::new(idx).into_raw() };
            0
        }
        Err(e) => {
            set_last_error(&format!("{e}"));
            unsafe { *out_handle = std::ptr::null_mut() };
            -3
        }
    }
}

/// Open a sidecar previously loaded into shared-memory-backed storage via
/// `prmi shm load`. `shm_path` is the path to the shm blob (typically
/// `/dev/shm/<name>` on Linux or `/tmp/<name>` on macOS).
///
/// Pages are mmap'd with `MAP_SHARED`; multiple processes opening the same
/// `shm_path` share OS page-cache pages without re-paying I/O or page-fault
/// costs after the first open.
///
/// Returns 0 on success and writes the handle to `*out_handle`. Returns
/// negative on error; `*out_handle` is set to NULL.
///
/// Post-open semantics are identical to `prmi_open`. The handle must be
/// closed with `prmi_close`.
///
/// Thread-safe after return.
///
/// # Safety
/// `shm_path` must be a valid NUL-terminated C string. `out_handle` must be
/// a valid writable pointer.
#[no_mangle]
pub unsafe extern "C" fn prmi_open_shm(
    shm_path: *const c_char,
    out_handle: *mut *mut prmi_index_t,
) -> c_int {
    clear_last_error();
    if shm_path.is_null() || out_handle.is_null() {
        set_last_error("prmi_open_shm: null pointer argument");
        // Clear any stale handle the caller is reusing (only when out_handle
        // itself is non-null and thus safe to write through).
        if !out_handle.is_null() {
            unsafe { *out_handle = std::ptr::null_mut() };
        }
        return -1;
    }
    let cstr = unsafe { CStr::from_ptr(shm_path) };
    let s = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => {
            set_last_error("prmi_open_shm: shm_path is not valid UTF-8");
            unsafe { *out_handle = std::ptr::null_mut() };
            return -2;
        }
    };
    match LearnedIndex::open_shm(std::path::Path::new(s)) {
        Ok(idx) => {
            unsafe { *out_handle = Handle::new(idx).into_raw() };
            0
        }
        Err(e) => {
            set_last_error(&format!("{e}"));
            unsafe { *out_handle = std::ptr::null_mut() };
            -3
        }
    }
}

/// Release all resources held by the handle. Safe to call with NULL.
///
/// # Safety
/// `handle` must be NULL or have been returned by `prmi_open` (or
/// `prmi_open_shm`) and not yet closed.
#[no_mangle]
pub unsafe extern "C" fn prmi_close(handle: *mut prmi_index_t) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Handle::from_raw(handle) });
}

/// Thread-local last-error string. Valid until the next prmi_* call on
/// the same thread. Never returns NULL — empty string if no error.
#[no_mangle]
pub extern "C" fn prmi_last_error_message() -> *const c_char {
    with_last_error(|c| c.as_ptr())
}

/// Predict the SA position for a 32-mer key.
///
/// Returns 0 on success; negative on error. Writes the predicted SA position
/// and the error bound to the out-pointers.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`. Both out-pointers must
/// be valid writable u64 locations.
#[no_mangle]
pub unsafe extern "C" fn prmi_lookup(
    handle: *const prmi_index_t,
    key: u64,
    out_predicted_sa_pos: *mut u64,
    out_err: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || out_predicted_sa_pos.is_null() || out_err.is_null() {
        set_last_error("prmi_lookup: null pointer argument");
        return -1;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let (pos, err) = h.idx.lookup(key);
    unsafe {
        *out_predicted_sa_pos = pos;
        *out_err = err;
    }
    0
}

/// Number of SA entries in the loaded sidecar.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`, or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn prmi_sa_num(handle: *const prmi_index_t) -> size_t {
    if handle.is_null() {
        return 0;
    }
    unsafe { Handle::as_ref(handle) }.idx.sa_num() as size_t
}

/// Whether the loaded sidecar carries an inverse suffix array (`.isa`), enabling
/// the `prmi_isa_at` launch hint / `mem_search` no-search fast path. Returns 1 if
/// present, else 0 (also 0 for a NULL handle or an shm-opened index, which does
/// not carry the `.isa`). The consumer branches on this at open time.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`, or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn prmi_has_isa(handle: *const prmi_index_t) -> c_int {
    if handle.is_null() {
        return 0;
    }
    c_int::from(unsafe { Handle::as_ref(handle) }.idx.has_isa())
}

/// Inverse suffix array lookup: given a reference position `refpos` (0-based in
/// the 2× doubled-coordinate space prmi indexes), write its SA index to
/// `*out_sa_index`. This is the exact launch hint to feed back as `est_hint` to
/// `prmi_mem_search` (BWA-MEME's `ref2sa`).
///
/// Returns 0 on success; `-1` null handle/out-ptr, `-2` `refpos >= sa_num`,
/// `-5` the loaded sidecar has no `.isa` (build with `prmi build --with-isa`).
///
/// # Safety
/// `handle` valid or NULL; `out_sa_index` writable on success.
#[no_mangle]
pub unsafe extern "C" fn prmi_isa_at(
    handle: *const prmi_index_t,
    refpos: u64,
    out_sa_index: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || out_sa_index.is_null() {
        set_last_error("prmi_isa_at: null handle or out_sa_index");
        return -1;
    }
    let h = unsafe { Handle::as_ref(handle) };
    if !h.idx.has_isa() {
        set_last_error("prmi_isa_at: sidecar has no .isa (build with --with-isa)");
        return -5;
    }
    if refpos >= h.idx.sa_num() {
        set_last_error("prmi_isa_at: refpos out of range");
        return -2;
    }
    // has_isa() is true and refpos < sa_num (== isa num_entries), so isa_at is Some.
    let sa_index = h
        .idx
        .isa_at(refpos)
        .expect("isa_at in range with .isa loaded");
    unsafe { *out_sa_index = sa_index };
    0
}

/// Global max prediction error stored in the sidecar.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open`, or NULL (returns 0).
#[no_mangle]
pub unsafe extern "C" fn prmi_max_error_bound(handle: *const prmi_index_t) -> u64 {
    if handle.is_null() {
        return 0;
    }
    unsafe { Handle::as_ref(handle) }.idx.max_error_bound()
}

/// Format magic string from the loaded sidecar (e.g. `"PRMIv2"`). Always non-NULL.
///
/// The returned pointer is valid for the lifetime of the handle. If `handle`
/// is NULL, returns a pointer to a static empty C string (`""`).
///
/// # Safety
/// `handle` may be NULL. If non-NULL, it must be a valid handle from
/// `prmi_open` or `prmi_open_shm` that has not yet been closed.
#[no_mangle]
pub unsafe extern "C" fn prmi_format_version(handle: *const prmi_index_t) -> *const c_char {
    static EMPTY: &[u8] = b"\0";
    if handle.is_null() {
        return EMPTY.as_ptr() as *const c_char;
    }
    unsafe { Handle::as_ref(handle) }.magic.as_ptr()
}

/// Tokenize up to 32 bases (2-bit packed, MSB-first, T-pad short queries)
/// into a u64 key suitable for prmi_lookup. Mirrors prmi's internal
/// tokenization exactly, so callers don't have to reimplement it.
///
/// `bases` points to at least `bases_len` unpacked bytes (values 0..=3).
/// `len` is the number of valid bases to use; values > 32 or > `bases_len`
/// are clamped to `min(len, bases_len, 32)`.
///
/// Returns 0 on success and writes the key to `*out_key`; returns -1 on
/// any pointer being null or `len < 0`.
///
/// # Safety
/// `bases` must point to at least `bases_len` valid bytes when `bases_len > 0`.
/// `out_key` must be a valid writable u64 location.
#[no_mangle]
pub unsafe extern "C" fn prmi_tokenize_32mer(
    bases: *const u8,
    bases_len: size_t,
    len: c_int,
    out_key: *mut u64,
) -> c_int {
    clear_last_error();
    if bases.is_null() || out_key.is_null() || len < 0 {
        set_last_error("prmi_tokenize_32mer: null pointer or negative len");
        return -1;
    }
    let n = (len as usize).min(32).min(bases_len);
    let slice = unsafe { std::slice::from_raw_parts(bases, n) };
    let key = prmi::encoding::tokenize_32mer(slice, n);
    unsafe { *out_key = key };
    0
}

/// Read `count` SA positions starting at SA index `k` into the
/// caller-provided `out_positions` buffer.
///
/// `out_positions` must point to at least `count` u64s. Each position
/// is a forward-strand genome offset (per the sidecar's `[sa] strand`
/// convention). For reverse-strand matches, tokenize the
/// reverse-complement of the query and call `prmi_lookup` a second time.
///
/// Returns 0 on success and 0 with no writes if `count == 0`. Error codes:
///   - `-1` — `handle` is NULL.
///   - `-2` — `out_positions` is NULL with `count > 0`.
///   - `-3` — `count` does not fit in `usize` on this target.
///   - `-4` — range `[k, k + count)` exceeds `sa_num`, or another internal
///     error from `LearnedIndex::sa_positions`; see `prmi_last_error_message`.
///
/// These codes are part of the stable ABI; downstream callers may match
/// against them. `prmi_last_error_message()` always carries a human-readable
/// description.
///
/// Thread-safe: concurrent calls on the same handle are intended and safe.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open` (or NULL → error).
/// `out_positions` must point to writable memory of size
/// `count * sizeof(uint64_t)` when count > 0.
#[no_mangle]
pub unsafe extern "C" fn prmi_sa_positions(
    handle: *const prmi_index_t,
    k: u64,
    count: u64,
    out_positions: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() {
        set_last_error("prmi_sa_positions: NULL handle");
        return -1;
    }
    if count == 0 {
        return 0;
    }
    if out_positions.is_null() {
        set_last_error("prmi_sa_positions: NULL out_positions with count > 0");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let count_usize = match usize::try_from(count) {
        Ok(c) => c,
        Err(_) => {
            set_last_error("prmi_sa_positions: count exceeds usize range");
            return -3;
        }
    };
    let slice = unsafe { std::slice::from_raw_parts_mut(out_positions, count_usize) };
    match h.idx.sa_positions(k, slice) {
        Ok(()) => 0,
        Err(e) => {
            set_last_error(&format!("prmi_sa_positions: {e}"));
            -4
        }
    }
}

/// Read `n_out` raw 2× SA positions starting at SA index `k`, sampling every
/// `step`-th entry: `out[j] = SA[k + j*step]`. Mirrors the FMI's strided fetch
/// for the `>max_occ` path (caller sets `step = s / max_occ`, `n_out = max_occ`).
///
/// Returns 0 on success; 0 with no writes if `n_out == 0`. Error codes:
///   - `-1` — `handle` is NULL.
///   - `-2` — `out_positions` is NULL with `n_out > 0`.
///   - `-3` — `n_out` does not fit in `usize` on this target.
///   - `-4` — last index `k + (n_out-1)*step >= sa_num`, overflow, or another
///     internal error from `LearnedIndex::sa_positions_strided`; see
///     `prmi_last_error_message`.
///
/// These codes are part of the stable ABI. `prmi_last_error_message()` always
/// carries a human-readable description.
///
/// Thread-safe: concurrent calls on the same handle are intended and safe.
///
/// # Safety
/// `handle` must be a valid handle from `prmi_open` (or NULL → error).
/// `out_positions` must point to writable memory of size
/// `n_out * sizeof(uint64_t)` when `n_out > 0`.
#[no_mangle]
pub unsafe extern "C" fn prmi_sa_positions_strided(
    handle: *const prmi_index_t,
    k: u64,
    step: u64,
    n_out: u64,
    out_positions: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() {
        set_last_error("prmi_sa_positions_strided: NULL handle");
        return -1;
    }
    if n_out == 0 {
        return 0;
    }
    if out_positions.is_null() {
        set_last_error("prmi_sa_positions_strided: NULL out_positions with n_out > 0");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let n_out_usize = match usize::try_from(n_out) {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_sa_positions_strided: n_out exceeds usize range");
            return -3;
        }
    };
    let out = unsafe { std::slice::from_raw_parts_mut(out_positions, n_out_usize) };
    match h.idx.sa_positions_strided(k, step, out) {
        Ok(()) => 0,
        Err(e) => {
            set_last_error(&format!("prmi_sa_positions_strided: {e}"));
            -4
        }
    }
}

/// One SMEM spectrum breakpoint: the SA interval `[sa_start, sa_start+occ_count)`
/// matching the query to length `match_len`. Mirrors `prmi::index::spectrum::SmemStep`.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct prmi_smem_step_t {
    /// SA interval start index (raw 2× SA).
    pub sa_start: u64,
    /// Occurrence count = SA interval size (both strands, native to the 2× SA).
    pub occ_count: u64,
    /// Match length (LCP) at this breakpoint.
    pub match_len: u64,
}

/// `prmi_smem_step_t` and `prmi::index::spectrum::SmemStep` are both `#[repr(C)]`
/// with the same three `u64` fields in the same order, so an output buffer of
/// one can be filled in place as a slice of the other (used by the `*_fill`
/// paths below to avoid an intermediate `Vec`). This assertion guards
/// size/alignment; the field order is asserted by inspection and the `#[repr(C)]`
/// on both types (see `SmemStep`'s doc comment).
const _: () = {
    assert!(
        core::mem::size_of::<prmi_smem_step_t>()
            == core::mem::size_of::<prmi::index::spectrum::SmemStep>()
    );
    assert!(
        core::mem::align_of::<prmi_smem_step_t>()
            == core::mem::align_of::<prmi::index::spectrum::SmemStep>()
    );
};

/// Reinterpret a `prmi_smem_step_t` output buffer as a `SmemStep` slice so the
/// search core can fill it directly. Sound by the layout equivalence asserted
/// above.
///
/// # Safety
/// `out_steps` must be non-null and point to at least `len` writable
/// `prmi_smem_step_t` slots.
#[inline]
unsafe fn out_steps_as_smemstep<'a>(
    out_steps: *mut prmi_smem_step_t,
    len: usize,
) -> &'a mut [prmi::index::spectrum::SmemStep] {
    unsafe {
        std::slice::from_raw_parts_mut(out_steps as *mut prmi::index::spectrum::SmemStep, len)
    }
}

/// Forward spectrum from a pivot: writes the breakpoint trace (ascending match_len,
/// up to the maximal forward match) into the caller-allocated `out_steps`
/// (capacity `max_steps`), and the count to `*out_nsteps`. `nsteps <= query_len`,
/// so `max_steps >= query_len` always suffices.
///
/// `query` = read[pivot..], 2-bit 0..3. `pac` is the FORWARD pac in BWA bntpac
/// packed form (4 bases/byte); `pac_num_bases` = l_pac.
///
/// Returns 0 on success (out_nsteps may be 0 = no match), negative on error:
///   -1 null handle, -2 null/invalid arg, query_len<=0, pac_num_bases too large
///      for this platform, or max_steps beyond usize range, -3 internal/panic,
///   -4 max_steps < produced nsteps (buffer too small; *out_nsteps set to needed;
///      the first max_steps entries are written — re-run with a larger buffer).
///
/// # Safety
/// All pointers valid; `query` has `query_len` bytes; `pac` has
/// `ceil(pac_num_bases/4)` bytes; `out_steps` has capacity `max_steps`.
#[no_mangle]
pub unsafe extern "C" fn prmi_forward_spectrum(
    handle: *const prmi_index_t,
    query: *const u8,
    query_len: c_int,
    pac: *const u8,
    pac_num_bases: u64,
    out_steps: *mut prmi_smem_step_t,
    max_steps: u64,
    out_nsteps: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null()
        || query.is_null()
        || pac.is_null()
        || out_steps.is_null()
        || out_nsteps.is_null()
    {
        set_last_error("prmi_forward_spectrum: null pointer argument");
        return -1;
    }
    if query_len <= 0 {
        set_last_error("prmi_forward_spectrum: query_len must be > 0");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let q = unsafe { std::slice::from_raw_parts(query, query_len as usize) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error("prmi_forward_spectrum: pac_num_bases too large for this platform");
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };

    // Fill the caller's buffer directly (no intermediate Vec). `_fill` returns
    // the TOTAL step count even when it exceeds the buffer, so overflow is
    // detected without allocating. Guard the u64→usize narrowing so a buffer
    // length past `usize::MAX` (32-bit targets) can't silently truncate `out`.
    let max_steps_usize = match usize::try_from(max_steps) {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_forward_spectrum: max_steps exceeds usize range");
            return -2;
        }
    };
    let out = unsafe { out_steps_as_smemstep(out_steps, max_steps_usize) };
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        // `_auto` transparently uses the loaded `.kmt` table when present
        // (byte-identical output), else the full search.
        h.idx.forward_spectrum_auto_fill(q, pac_slice, enc, out)
    }));
    let nsteps = match result {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_forward_spectrum: internal panic");
            return -3;
        }
    };
    unsafe { *out_nsteps = nsteps as u64 };
    if nsteps as u64 > max_steps {
        set_last_error("prmi_forward_spectrum: max_steps too small");
        return -4;
    }
    0
}

/// Backward spectrum: refine a right-anchored interval leftward. `(sa_start,
/// occ_count)` and `anchor_len` come from a prior `prmi_forward_spectrum` step.
/// Each emitted step's `match_len` is the TOTAL span (`left_ext + anchor_len`).
/// Writes the trace into `out_steps` (capacity `max_steps`; `nsteps <= pivot+1`)
/// and the count to `*out_nsteps`. `read` is the full read (2-bit 0..=3, 1
/// base per byte); `pivot` = index where the right anchor begins (i.e.
/// `read[pivot..pivot+anchor_len)` is the anchored query). `pac` is the FORWARD
/// pac (BWA bntpac packed: 4 bases/byte, MSB-first); `pac_num_bases` = l_pac.
///
/// Returns 0 on success (out_nsteps may be 0 = no left extension exists),
/// negative on error:
///   -1 null handle/pointer, -2 invalid read_len (<=0)/pivot (<0), pac_num_bases
///      too large for this platform, or max_steps beyond usize range,
///   -3 internal/panic (including a contiguity-guard failure on a corrupt index),
///   -4 max_steps too small (*out_nsteps set to the needed count; the first
///      max_steps entries are written — re-run with a larger buffer).
///
/// # Safety
/// All pointers valid; `read` has `read_len` bytes; `pac` has
/// `ceil(pac_num_bases/4)` bytes; `out_steps` has capacity `max_steps`.
#[no_mangle]
pub unsafe extern "C" fn prmi_backward_spectrum(
    handle: *const prmi_index_t,
    sa_start: u64,
    occ_count: u64,
    anchor_len: u64,
    read: *const u8,
    read_len: c_int,
    pivot: c_int,
    pac: *const u8,
    pac_num_bases: u64,
    out_steps: *mut prmi_smem_step_t,
    max_steps: u64,
    out_nsteps: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null()
        || read.is_null()
        || pac.is_null()
        || out_steps.is_null()
        || out_nsteps.is_null()
    {
        set_last_error("prmi_backward_spectrum: null pointer argument");
        return -1;
    }
    if read_len <= 0 || pivot < 0 {
        set_last_error("prmi_backward_spectrum: invalid read_len or pivot");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let r = unsafe { std::slice::from_raw_parts(read, read_len as usize) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error("prmi_backward_spectrum: pac_num_bases too large for this platform");
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };
    let pivot_us = pivot as usize;

    // Fill the caller's buffer directly (no intermediate Vec). Guard the
    // u64→usize narrowing so a buffer length past `usize::MAX` (32-bit targets)
    // can't silently truncate `out`.
    let max_steps_usize = match usize::try_from(max_steps) {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_backward_spectrum: max_steps exceeds usize range");
            return -2;
        }
    };
    let out = unsafe { out_steps_as_smemstep(out_steps, max_steps_usize) };
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        h.idx.backward_spectrum_fill(
            sa_start, occ_count, anchor_len, r, pivot_us, pac_slice, enc, out,
        )
    }));
    let nsteps = match result {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_backward_spectrum: internal panic (possible corrupt SA/ISA)");
            return -3;
        }
    };
    unsafe { *out_nsteps = nsteps as u64 };
    if nsteps as u64 > max_steps {
        set_last_error("prmi_backward_spectrum: max_steps too small");
        return -4;
    }
    0
}

/// One forward-spectrum batch task: read `query_len` bytes at `query_off` in the
/// shared queries arena; write up to `max_steps` steps at index `steps_off` in the
/// shared steps arena.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct prmi_fwd_task_t {
    /// Byte offset into the queries arena where this task's query begins.
    pub query_off: u64,
    /// Number of query bytes (= query length in bases).
    pub query_len: u32,
    /// Step index (not byte offset) into the steps arena where this task writes.
    pub steps_off: u32,
    /// Maximum number of steps this task may write; 0 triggers the -4 overflow path.
    pub max_steps: u32,
}

/// One backward-spectrum batch task.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct prmi_bwd_task_t {
    /// SA interval start (from a prior forward step).
    pub sa_start: u64,
    /// Occurrence count (from a prior forward step).
    pub occ_count: u64,
    /// Anchor match length (from a prior forward step).
    pub anchor_len: u64,
    /// Byte offset into the reads arena where this task's read begins.
    pub read_off: u64,
    /// Number of read bytes.
    pub read_len: u32,
    /// Pivot index within the read (where the right anchor starts).
    pub pivot: u32,
    /// Step index into the steps arena where this task writes.
    pub steps_off: u32,
    /// Maximum number of steps this task may write.
    pub max_steps: u32,
}

/// Run `ntasks` forward spectra (correctness-first loop; lockstep
/// predict→prefetch→compare is a deferred perf optimization — see the design
/// spec). `queries_arena` holds all task query bytes (2-bit 0..3, caller-owned,
/// NOT copied); `queries_arena_len` is its size in bytes. Task i reads
/// `query_len` bytes at `query_off`. `steps_arena` is a shared caller-owned
/// output arena; `steps_arena_len` is its capacity in `prmi_smem_step_t`
/// elements. Task i writes up to `max_steps` steps starting at index
/// `steps_off`, and its produced count to `out_nsteps[i]` (0 if no match).
/// `pac` is the FORWARD pac (packed); `pac_num_bases` = l_pac.
///
/// Returns 0 on success. Error codes:
///   - `-1` — null pointer (with ntasks>0).
///   - `-2` — a task descriptor's query or steps window falls outside its arena,
///     or `ntasks` / a task's `query_off` / the packed pac length does not fit
///     `usize` on this target
///     (bad programming error); `prmi_last_error_message` names the offending
///     task index and which window violated the bound. The whole batch is
///     aborted on the first violation; no arena memory is read or written for
///     the violating task.
///   - `-3` — internal/panic.
///   - `-4` — a task's produced nsteps exceeds its `max_steps`; that task's
///     `out_nsteps[i]` is set to the needed count; its steps region is left
///     unwritten/partial — caller should re-run that task with a larger buffer.
///
/// # Safety
/// All pointers valid for their declared sizes; arenas at least as large as
/// declared; `out_nsteps` has `ntasks` u64 slots.
#[no_mangle]
pub unsafe extern "C" fn prmi_forward_spectrum_batch(
    handle: *const prmi_index_t,
    queries_arena: *const u8,
    queries_arena_len: u64,
    tasks: *const prmi_fwd_task_t,
    ntasks: u64,
    pac: *const u8,
    pac_num_bases: u64,
    steps_arena: *mut prmi_smem_step_t,
    steps_arena_len: u64,
    out_nsteps: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || pac.is_null() {
        set_last_error("prmi_forward_spectrum_batch: null pointer");
        return -1;
    }
    if ntasks == 0 {
        return 0;
    }
    if queries_arena.is_null() || tasks.is_null() || steps_arena.is_null() || out_nsteps.is_null() {
        set_last_error("prmi_forward_spectrum_batch: null arena/tasks/out with ntasks > 0");
        return -1;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error(
                "prmi_forward_spectrum_batch: pac_num_bases too large for this platform",
            );
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };
    let nt = match usize::try_from(ntasks) {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_forward_spectrum_batch: ntasks exceeds usize range");
            return -2;
        }
    };
    let tasks_s = unsafe { std::slice::from_raw_parts(tasks, nt) };
    let out_ns = unsafe { std::slice::from_raw_parts_mut(out_nsteps, nt) };

    // Validate all task descriptors against arena bounds before any I/O.
    for (i, t) in tasks_s.iter().enumerate() {
        // Guard the u64→usize narrowing used by `queries_arena.add(query_off)`
        // below; on a narrow-`usize` target a huge offset would misaddress.
        if usize::try_from(t.query_off).is_err() {
            set_last_error(&format!(
                "prmi_forward_spectrum_batch: task {i} query_off={} exceeds usize range",
                t.query_off
            ));
            return -2;
        }
        let query_end = (t.query_off as u128)
            .checked_add(t.query_len as u128)
            .map(|e| e <= queries_arena_len as u128)
            .unwrap_or(false);
        if !query_end {
            set_last_error(&format!(
                "prmi_forward_spectrum_batch: task {i} query window \
                 [query_off={}, query_len={}] out of queries_arena_len={}",
                t.query_off, t.query_len, queries_arena_len
            ));
            return -2;
        }
        let steps_end = (t.steps_off as u128)
            .checked_add(t.max_steps as u128)
            .map(|e| e <= steps_arena_len as u128)
            .unwrap_or(false);
        if !steps_end {
            set_last_error(&format!(
                "prmi_forward_spectrum_batch: task {i} steps window \
                 [steps_off={}, max_steps={}] out of steps_arena_len={}",
                t.steps_off, t.max_steps, steps_arena_len
            ));
            return -2;
        }
    }

    // One catch_unwind around the whole loop — panic anywhere → -3.
    let mut overflow = false;
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        for (i, t) in tasks_s.iter().enumerate() {
            let q = unsafe {
                std::slice::from_raw_parts(
                    queries_arena.add(t.query_off as usize),
                    t.query_len as usize,
                )
            };
            // Fill this task's arena region directly; `_fill` returns the total
            // count and writes at most `max_steps` steps (overflow → -4, caller
            // retries with a larger buffer).
            let dst = unsafe {
                out_steps_as_smemstep(steps_arena.add(t.steps_off as usize), t.max_steps as usize)
            };
            let nsteps = h.idx.forward_spectrum_auto_fill(q, pac_slice, enc, dst);
            out_ns[i] = nsteps as u64;
            if nsteps as u64 > u64::from(t.max_steps) {
                overflow = true;
            }
        }
    }));
    if res.is_err() {
        set_last_error("prmi_forward_spectrum_batch: internal panic");
        return -3;
    }
    if overflow {
        set_last_error("prmi_forward_spectrum_batch: a task's max_steps too small");
        return -4;
    }
    0
}

/// Write one backward task's steps into the shared `steps_arena`, setting
/// `*out_ns_i` to the step count. Returns `true` if the count exceeded
/// `t.max_steps` (the task's arena region is then left unwritten for the caller
/// to retry with a larger buffer). Used by the lockstep arm, whose
/// `backward_spectrum_lockstep` returns owned step vectors; the serial arm fills
/// the arena directly via `backward_spectrum_fill` instead.
///
/// # Safety
/// `steps_arena` must have at least `t.steps_off + steps.len()` slots.
#[inline]
unsafe fn write_bwd_task_steps(
    steps_arena: *mut prmi_smem_step_t,
    t: &prmi_bwd_task_t,
    steps: &[prmi::index::spectrum::SmemStep],
    out_ns_i: &mut u64,
) -> bool {
    *out_ns_i = steps.len() as u64;
    if steps.len() as u64 > u64::from(t.max_steps) {
        return true;
    }
    let dst = unsafe {
        std::slice::from_raw_parts_mut(steps_arena.add(t.steps_off as usize), steps.len())
    };
    for (slot, s) in dst.iter_mut().zip(steps.iter()) {
        *slot = prmi_smem_step_t {
            sa_start: s.sa_start,
            occ_count: s.occ_count,
            match_len: s.match_len,
        };
    }
    false
}

/// Shared impl for the two backward-batch entry points. `lockstep == false` runs
/// the correctness-first serial loop (one `backward_spectrum` per task);
/// `lockstep == true` drives all tasks through `backward_spectrum_lockstep`
/// (memory-level parallelism via batched probe loads). Output is byte-identical
/// between the two strategies — they differ only in execution order and timing.
///
/// # Safety
/// All pointers valid for their declared sizes; arenas at least as large as
/// declared; `out_nsteps` has `ntasks` u64 slots.
#[allow(clippy::too_many_arguments)]
unsafe fn backward_spectrum_batch_impl(
    handle: *const prmi_index_t,
    reads_arena: *const u8,
    reads_arena_len: u64,
    tasks: *const prmi_bwd_task_t,
    ntasks: u64,
    pac: *const u8,
    pac_num_bases: u64,
    steps_arena: *mut prmi_smem_step_t,
    steps_arena_len: u64,
    out_nsteps: *mut u64,
    lockstep: bool,
) -> c_int {
    clear_last_error();
    if handle.is_null() || pac.is_null() {
        set_last_error("prmi_backward_spectrum_batch: null pointer");
        return -1;
    }
    if ntasks == 0 {
        return 0;
    }
    if reads_arena.is_null() || tasks.is_null() || steps_arena.is_null() || out_nsteps.is_null() {
        set_last_error("prmi_backward_spectrum_batch: null arena/tasks/out with ntasks > 0");
        return -1;
    }
    let h = unsafe { Handle::as_ref(handle) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error(
                "prmi_backward_spectrum_batch: pac_num_bases too large for this platform",
            );
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };
    let nt = match usize::try_from(ntasks) {
        Ok(n) => n,
        Err(_) => {
            set_last_error("prmi_backward_spectrum_batch: ntasks exceeds usize range");
            return -2;
        }
    };
    let tasks_s = unsafe { std::slice::from_raw_parts(tasks, nt) };
    let out_ns = unsafe { std::slice::from_raw_parts_mut(out_nsteps, nt) };

    // Validate all task descriptors against arena bounds before any I/O.
    for (i, t) in tasks_s.iter().enumerate() {
        // Guard the u64→usize narrowing used by `reads_arena.add(read_off)`
        // below; on a narrow-`usize` target a huge offset would misaddress.
        if usize::try_from(t.read_off).is_err() {
            set_last_error(&format!(
                "prmi_backward_spectrum_batch: task {i} read_off={} exceeds usize range",
                t.read_off
            ));
            return -2;
        }
        let read_end = (t.read_off as u128)
            .checked_add(t.read_len as u128)
            .map(|e| e <= reads_arena_len as u128)
            .unwrap_or(false);
        if !read_end {
            set_last_error(&format!(
                "prmi_backward_spectrum_batch: task {i} read window \
                 [read_off={}, read_len={}] out of reads_arena_len={}",
                t.read_off, t.read_len, reads_arena_len
            ));
            return -2;
        }
        let steps_end = (t.steps_off as u128)
            .checked_add(t.max_steps as u128)
            .map(|e| e <= steps_arena_len as u128)
            .unwrap_or(false);
        if !steps_end {
            set_last_error(&format!(
                "prmi_backward_spectrum_batch: task {i} steps window \
                 [steps_off={}, max_steps={}] out of steps_arena_len={}",
                t.steps_off, t.max_steps, steps_arena_len
            ));
            return -2;
        }
    }

    // One catch_unwind around the whole batch — panic anywhere (incl. contiguity
    // guard in backward_spectrum) → -3.
    let mut overflow = false;
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        if lockstep {
            // Lockstep genuinely needs all tasks resident at once:
            // `backward_spectrum_lockstep` drives them together for memory-level
            // parallelism and returns one step vector per task. Write each result
            // through after the batched call.
            let bwd_tasks: Vec<_> = tasks_s
                .iter()
                .map(|t| {
                    let read = unsafe {
                        std::slice::from_raw_parts(
                            reads_arena.add(t.read_off as usize),
                            t.read_len as usize,
                        )
                    };
                    prmi::index::spectrum::BwdTask {
                        sa_start: t.sa_start,
                        occ_count: t.occ_count,
                        anchor_len: t.anchor_len,
                        read,
                        pivot: t.pivot as usize,
                    }
                })
                .collect();
            let all_steps = h.idx.backward_spectrum_lockstep(&bwd_tasks, pac_slice, enc);
            for (i, steps) in all_steps.iter().enumerate() {
                if unsafe { write_bwd_task_steps(steps_arena, &tasks_s[i], steps, &mut out_ns[i]) }
                {
                    overflow = true;
                }
            }
        } else {
            // Serial: fill each task's arena region directly (mirroring
            // prmi_forward_spectrum_batch), with no per-task or whole-batch Vec.
            for (i, t) in tasks_s.iter().enumerate() {
                let read = unsafe {
                    std::slice::from_raw_parts(
                        reads_arena.add(t.read_off as usize),
                        t.read_len as usize,
                    )
                };
                let dst = unsafe {
                    out_steps_as_smemstep(
                        steps_arena.add(t.steps_off as usize),
                        t.max_steps as usize,
                    )
                };
                let nsteps = h.idx.backward_spectrum_fill(
                    t.sa_start,
                    t.occ_count,
                    t.anchor_len,
                    read,
                    t.pivot as usize,
                    pac_slice,
                    enc,
                    dst,
                );
                out_ns[i] = nsteps as u64;
                if nsteps as u64 > u64::from(t.max_steps) {
                    overflow = true;
                }
            }
        }
    }));
    if res.is_err() {
        set_last_error("prmi_backward_spectrum_batch: internal panic");
        return -3;
    }
    if overflow {
        set_last_error("prmi_backward_spectrum_batch: a task's max_steps too small");
        return -4;
    }
    0
}

/// Run `ntasks` backward spectra with the correctness-first SERIAL strategy (one
/// `backward_spectrum` per task). This is the safe default: it never regresses
/// relative to calling `prmi_backward_spectrum` in a loop, and it amortizes the
/// FFI crossing. `reads_arena` holds all task read bytes (2-bit 0..3, caller-
/// owned, NOT copied); `reads_arena_len` is its size in bytes. Task i reads
/// `read_len` bytes at `read_off`. `steps_arena` is a shared caller-owned output
/// arena; `steps_arena_len` is its capacity in `prmi_smem_step_t` elements.
/// Task i writes up to `max_steps` steps at index `steps_off`, and its count to
/// `out_nsteps[i]` (0 if no left extension). `pac` is the FORWARD pac (packed);
/// `pac_num_bases` = l_pac.
///
/// For the memory-level-parallelism variant, see
/// `prmi_backward_spectrum_batch_lockstep` — byte-identical output, faster on
/// high-DRAM-latency microarchitectures, slower on low-latency ones (measure).
///
/// Returns 0 on success. Error codes:
///   - `-1` — null pointer (with ntasks>0).
///   - `-2` — a task descriptor's read or steps window falls outside its arena,
///     or `ntasks` / a task's `read_off` / the packed pac length does not fit
///     `usize` on this target;
///     `prmi_last_error_message` names the offending task index and window. The
///     whole batch is aborted on the first violation; no arena memory is read or
///     written for the violating task.
///   - `-3` — internal/panic (including a contiguity-guard failure).
///   - `-4` — a task's produced nsteps exceeds its `max_steps`; that task's
///     `out_nsteps[i]` is set to the needed count; its steps region is left
///     unwritten/partial.
///
/// # Safety
/// All pointers valid for their declared sizes; arenas at least as large as
/// declared; `out_nsteps` has `ntasks` u64 slots.
#[no_mangle]
pub unsafe extern "C" fn prmi_backward_spectrum_batch(
    handle: *const prmi_index_t,
    reads_arena: *const u8,
    reads_arena_len: u64,
    tasks: *const prmi_bwd_task_t,
    ntasks: u64,
    pac: *const u8,
    pac_num_bases: u64,
    steps_arena: *mut prmi_smem_step_t,
    steps_arena_len: u64,
    out_nsteps: *mut u64,
) -> c_int {
    unsafe {
        backward_spectrum_batch_impl(
            handle,
            reads_arena,
            reads_arena_len,
            tasks,
            ntasks,
            pac,
            pac_num_bases,
            steps_arena,
            steps_arena_len,
            out_nsteps,
            false,
        )
    }
}

/// Run `ntasks` backward spectra with the LOCKSTEP strategy: all tasks are driven
/// in parallel, batching their cold SA/model probe loads each round so the memory
/// latency overlaps (memory-level parallelism). Byte-identical output to
/// `prmi_backward_spectrum_batch` — same intervals, same order — differing only
/// in execution strategy. Faster on high-DRAM-latency microarchitectures (server
/// x86 / Graviton); can be SLOWER on low-latency ones (e.g. Apple Silicon, which
/// already hides the latency). A/B both entry points on the target hardware and
/// pick the winner. Same arguments, arena contract, and error codes as
/// `prmi_backward_spectrum_batch`.
///
/// # Safety
/// All pointers valid for their declared sizes; arenas at least as large as
/// declared; `out_nsteps` has `ntasks` u64 slots.
#[no_mangle]
pub unsafe extern "C" fn prmi_backward_spectrum_batch_lockstep(
    handle: *const prmi_index_t,
    reads_arena: *const u8,
    reads_arena_len: u64,
    tasks: *const prmi_bwd_task_t,
    ntasks: u64,
    pac: *const u8,
    pac_num_bases: u64,
    steps_arena: *mut prmi_smem_step_t,
    steps_arena_len: u64,
    out_nsteps: *mut u64,
) -> c_int {
    unsafe {
        backward_spectrum_batch_impl(
            handle,
            reads_arena,
            reads_arena_len,
            tasks,
            ntasks,
            pac,
            pac_num_bases,
            steps_arena,
            steps_arena_len,
            out_nsteps,
            true,
        )
    }
}

/// `PRMI_MEM_WANT_INTERVAL`: also write `*out_sa_start`/`*out_occ` (the maximal
/// match's SA interval). When unset, only `*out_match_len` is written.
pub const PRMI_MEM_WANT_INTERVAL: u32 = 0x1;

/// One-shot maximal exact forward match. `query` is 2-bit bases (direction/RC
/// already applied by the caller); finds the longest prefix that occurs in the
/// reference. `*out_match_len` is ALWAYS written (0 if `query[0]` has no match).
/// With `flags & PRMI_MEM_WANT_INTERVAL`, also writes `*out_sa_start`/`*out_occ`
/// (the SA interval at `match_len`).
///
/// `est_hint`: `0` → prmi does its own model launch (full search). `> 0` → an
/// EXACT inverse-SA hint (from `prmi_isa_at(refpos)`): prmi confirms+extends from
/// that exact suffix and skips the model launch and interval narrowing
/// (BWA-MEME's `no_search`/`mem_search_tradeoff`). The hint MUST be a SA index in
/// the query's maximal-match interval; the launch changes speed, never the answer
/// — the result is byte-identical to `est_hint == 0`. A hint `>= sa_num` returns
/// `-2`.
///
/// Byte-identity: the returned `(sa_start, occ, match_len)` equals the maximal
/// step `prmi_forward_spectrum` produces for the same query.
///
/// Returns 0 on success; `-1` null handle/pointer, `-2` `query_len < 0`,
/// `pac_num_bases` too large for this platform, or `est_hint >= sa_num`,
/// `-3` internal panic.
///
/// # Safety
/// `handle` valid; `query` valid for `query_len` bytes; `pac` valid for
/// `ceil(pac_num_bases/4)` bytes; `out_match_len` writable; with the flag,
/// `out_sa_start`/`out_occ` writable.
#[no_mangle]
pub unsafe extern "C" fn prmi_mem_search(
    handle: *const prmi_index_t,
    query: *const u8,
    query_len: c_int,
    pac: *const u8,
    pac_num_bases: u64,
    est_hint: u64,
    flags: u32,
    out_match_len: *mut u32,
    out_sa_start: *mut u64,
    out_occ: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || query.is_null() || pac.is_null() || out_match_len.is_null() {
        set_last_error("prmi_mem_search: null pointer");
        return -1;
    }
    // When the interval is requested, validate its out-ptrs up FRONT so an error
    // return leaves all outputs (incl. `*out_match_len`) untouched.
    if flags & PRMI_MEM_WANT_INTERVAL != 0 && (out_sa_start.is_null() || out_occ.is_null()) {
        set_last_error("prmi_mem_search: WANT_INTERVAL set but out_sa_start/out_occ null");
        return -1;
    }
    // NOTE: `< 0` (not `<= 0` as in `prmi_forward_spectrum`) is deliberate —
    // `query_len == 0` is a valid empty query and yields `match_len == 0`.
    if query_len < 0 {
        set_last_error("prmi_mem_search: query_len < 0");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    // est_hint == 0 → internal model launch; > 0 → exact ISA launch (no_search).
    // An out-of-range hint is a caller error (the spec's no_search contract is
    // that the hint is the exact in-interval SA index).
    if est_hint != 0 && est_hint >= h.idx.sa_num() {
        set_last_error("prmi_mem_search: est_hint out of range");
        return -2;
    }
    let want_interval = flags & PRMI_MEM_WANT_INTERVAL != 0;
    let q = unsafe { std::slice::from_raw_parts(query, query_len as usize) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error("prmi_mem_search: pac_num_bases too large for this platform");
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        if est_hint == 0 {
            h.idx.mem_search(q, pac_slice, enc)
        } else {
            h.idx
                .mem_search_from_hint(q, est_hint, want_interval, pac_slice, enc)
        }
    }));
    let m = match res {
        Ok(m) => m,
        Err(_) => {
            set_last_error("prmi_mem_search: internal panic");
            return -3;
        }
    };
    unsafe { *out_match_len = m.match_len as u32 };
    if flags & PRMI_MEM_WANT_INTERVAL != 0 {
        // out-ptrs were null-checked up front.
        unsafe {
            *out_sa_start = m.sa_start;
            *out_occ = m.occ;
        }
    }
    0
}

/// One-shot maximal exact BACKWARD (leftward) match — the backward twin of
/// `prmi_mem_search`. From the right anchor `(sa_start, occ_count, anchor_len)`
/// matching `read[pivot..pivot+anchor_len)`, extend leftward and return the
/// deepest match in a single call. Same `read`/`pivot` convention as
/// `prmi_backward_spectrum` (full read, 2-bit 1 base/byte; extension goes to
/// `read[pivot-1]`, `read[pivot-2]`, …).
///
/// `*out_match_len` is ALWAYS written = the TOTAL matched span
/// (`anchor_len + left_ext`). With `flags & PRMI_MEM_WANT_INTERVAL`, also writes
/// `*out_sa_start`/`*out_occ` (the SA interval at the maximal match). When no
/// left extension is possible the anchor itself is returned (`match_len ==
/// anchor_len`); when `occ_count == 0`, all-zero.
///
/// `est_hint`: `0` → model-launch backward search (uses `sa_start`/`occ_count`).
/// `> 0` → an EXACT inverse-SA hint (`prmi_isa_at(refpos)` for the anchor's
/// reference position): prmi confirms the left extension directly against the
/// reference and skips the per-step model launch (BWA-MEME's `no_search` for the
/// left direction). The hint REPLACES the anchor interval, so `sa_start`/
/// `occ_count` are ignored. The result is byte-identical to `est_hint == 0`
/// whenever the hint is at a maximal-extension locus; a stale/diverged hint
/// yields a SHORTER `*out_match_len` (the caller's signal to fall back to
/// `est_hint == 0`). A hint `>= sa_num` returns `-2`.
///
/// Byte-identity: the returned `(sa_start, occ, match_len)` equals the maximal
/// step `prmi_backward_spectrum` produces for the same inputs.
///
/// Returns 0 on success; `-1` null handle/pointer, `-2` `read_len <= 0`,
/// `pivot < 0`, `pac_num_bases` too large for this platform, or `est_hint >= sa_num`;
/// `-3` internal panic.
///
/// # Safety
/// `handle` valid; `read` valid for `read_len` bytes; `pac` valid for
/// `ceil(pac_num_bases/4)` bytes; `out_match_len` writable; with the flag,
/// `out_sa_start`/`out_occ` writable.
#[allow(clippy::too_many_arguments)]
#[no_mangle]
pub unsafe extern "C" fn prmi_mem_search_backward(
    handle: *const prmi_index_t,
    sa_start: u64,
    occ_count: u64,
    anchor_len: u64,
    read: *const u8,
    read_len: c_int,
    pivot: c_int,
    pac: *const u8,
    pac_num_bases: u64,
    est_hint: u64,
    flags: u32,
    out_match_len: *mut u32,
    out_sa_start: *mut u64,
    out_occ: *mut u64,
) -> c_int {
    clear_last_error();
    if handle.is_null() || read.is_null() || pac.is_null() || out_match_len.is_null() {
        set_last_error("prmi_mem_search_backward: null pointer");
        return -1;
    }
    // Validate interval out-ptrs up front so an error return leaves outputs
    // untouched (see prmi_mem_search).
    if flags & PRMI_MEM_WANT_INTERVAL != 0 && (out_sa_start.is_null() || out_occ.is_null()) {
        set_last_error("prmi_mem_search_backward: WANT_INTERVAL set but out_sa_start/out_occ null");
        return -1;
    }
    if read_len <= 0 || pivot < 0 {
        set_last_error("prmi_mem_search_backward: invalid read_len or pivot");
        return -2;
    }
    let h = unsafe { Handle::as_ref(handle) };
    // est_hint == 0 → model-launch backward search (uses sa_start/occ_count);
    // > 0 → exact ISA launch (no_search): the hint replaces the anchor interval,
    // so sa_start/occ_count are ignored. Out-of-range hint is a caller error.
    if est_hint != 0 && est_hint >= h.idx.sa_num() {
        set_last_error("prmi_mem_search_backward: est_hint out of range");
        return -2;
    }
    let want_interval = flags & PRMI_MEM_WANT_INTERVAL != 0;
    let r = unsafe { std::slice::from_raw_parts(read, read_len as usize) };
    let pac_bytes = match packed_pac_bytes(pac_num_bases) {
        Some(b) => b,
        None => {
            set_last_error("prmi_mem_search_backward: pac_num_bases too large for this platform");
            return -2;
        }
    };
    let pac_slice = unsafe { std::slice::from_raw_parts(pac, pac_bytes) };
    let enc = prmi::index::smem::PacEncoding::Packed {
        num_bases: pac_num_bases,
    };
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        if est_hint == 0 {
            h.idx.mem_search_backward(
                sa_start,
                occ_count,
                anchor_len,
                r,
                pivot as usize,
                pac_slice,
                enc,
            )
        } else {
            h.idx.mem_search_backward_from_hint(
                r,
                pivot as usize,
                anchor_len,
                est_hint,
                want_interval,
                pac_slice,
                enc,
            )
        }
    }));
    let m = match res {
        Ok(m) => m,
        Err(_) => {
            set_last_error("prmi_mem_search_backward: internal panic");
            return -3;
        }
    };
    unsafe { *out_match_len = m.match_len as u32 };
    if flags & PRMI_MEM_WANT_INTERVAL != 0 {
        unsafe {
            *out_sa_start = m.sa_start;
            *out_occ = m.occ;
        }
    }
    0
}

/// Reverse-complement a tokenized 32-mer key (2-bit packed, MSB-first).
/// `len` is the number of valid bases (1..=32; values outside that range
/// are clamped to 32). Writes the rev-comp key to *out_key.
///
/// Returns 0 on success; -1 if out_key is null.
///
/// # Safety
/// `out_key` must be a valid writable u64 location.
#[no_mangle]
pub unsafe extern "C" fn prmi_reverse_complement_key(
    key: u64,
    len: c_int,
    out_key: *mut u64,
) -> c_int {
    clear_last_error();
    if out_key.is_null() {
        set_last_error("prmi_reverse_complement_key: null out_key");
        return -1;
    }
    // Match main's FFI contract: a non-positive `len` (including 0) means "use
    // the full 32-mer", not "zero valid bases" — callers pass 0 to mean a full
    // key, never an empty one.
    let n = if len <= 0 { 32 } else { (len as usize).min(32) };
    let rc = prmi::encoding::reverse_complement_key(key, n);
    unsafe { *out_key = rc };
    0
}

/// Reverse-complement a 2-bit unpacked base array (1 base per byte,
/// values 0..=3; A=0, C=1, G=2, T=3). Writes `len` bytes to `out`.
///
/// `in_` and `out` may overlap arbitrarily. The common cases — `out == in_` (an
/// in-place transform) and fully disjoint buffers — take an allocation-free
/// two-ended walk, reading each pair before writing it so full alias is correct.
/// The rare PARTIAL-overlap case (the buffers share some but not all bytes, where
/// the two-ended walk would clobber not-yet-read input) falls back to a scratch
/// buffer, preserving the byte-identical result of the prior implementation.
///
/// Returns 0 on success; -1 if `in_` or `out` is null, or `len < 0`.
///
/// # Safety
/// `in_` must point to at least `len` valid bytes when `len > 0`.
/// `out` must point to at least `len` writable bytes when `len > 0`.
#[no_mangle]
pub unsafe extern "C" fn prmi_reverse_complement_2bit(
    in_: *const u8,
    len: c_int,
    out: *mut u8,
) -> c_int {
    clear_last_error();
    if in_.is_null() || out.is_null() || len < 0 {
        set_last_error("prmi_reverse_complement_2bit: null pointer or negative len");
        return -1;
    }
    let n = len as usize;
    if n == 0 {
        return 0;
    }
    // Partial overlap (buffers share some but not all bytes, and `out != in_`)
    // is the only case the in-place two-ended walk cannot handle: writing one end
    // would clobber input the opposite end has not read yet. Detect it by raw
    // pointer ranges and fall back to a scratch buffer, matching the prior
    // (always-allocating) implementation byte-for-byte. Full alias (`out == in_`)
    // and disjoint buffers take the allocation-free fast path below.
    let in_start = in_ as usize;
    let out_start = out as usize;
    let in_end = in_start.saturating_add(n);
    let out_end = out_start.saturating_add(n);
    let partial_overlap = in_start != out_start && in_start < out_end && out_start < in_end;
    if partial_overlap {
        let mut tmp = Vec::with_capacity(n);
        unsafe {
            for i in 0..n {
                tmp.push((*in_.add(n - 1 - i) & 0x3) ^ 0x3);
            }
            std::ptr::copy_nonoverlapping(tmp.as_ptr(), out, n);
        }
        return 0;
    }
    // Two-ended complement-and-reverse directly into `out`, no allocation. Each
    // pair is read into locals before either end is written, so this is correct
    // even when `out` and `in_` fully overlap (alias the same buffer). Raw
    // pointer reads/writes (not slices) avoid forming aliasing &/&mut.
    unsafe {
        let mut lo = 0usize;
        let mut hi = n - 1;
        while lo < hi {
            let a = *in_.add(lo);
            let b = *in_.add(hi);
            *out.add(lo) = (b & 0x3) ^ 0x3;
            *out.add(hi) = (a & 0x3) ^ 0x3;
            lo += 1;
            hi -= 1;
        }
        if lo == hi {
            // Odd length: complement the middle base in place.
            let m = *in_.add(lo);
            *out.add(lo) = (m & 0x3) ^ 0x3;
        }
    }
    0
}
