// Copyright (C) 2026 Fulcrum Genomics LLC
// SPDX-License-Identifier: MIT

//! C FFI shim for prmi. See `include/prmi.h` (generated by build.rs).

#![allow(non_camel_case_types)]

mod errors;
mod handle;

use crate::errors::{clear_last_error, set_last_error, with_last_error};
use crate::handle::{prmi_index_t, Handle};
use prmi::index::LearnedIndex;
use std::ffi::CStr;
use std::os::raw::{c_char, c_int};
use std::path::Path;

/// Open a sidecar by prefix; expects <prefix>.{meta,sa,l1,l2}.
///
/// Returns 0 on success and writes the handle to *out_handle.
/// Returns negative on error; *out_handle is set to NULL.
///
/// # Safety
/// `sidecar_prefix` must be a valid NUL-terminated C string. `out_handle`
/// must be a valid writable pointer.
#[no_mangle]
pub unsafe extern "C" fn prmi_open(
    sidecar_prefix: *const c_char,
    out_handle: *mut *mut prmi_index_t,
) -> c_int {
    clear_last_error();
    if sidecar_prefix.is_null() || out_handle.is_null() {
        set_last_error("prmi_open: null pointer argument");
        return -1;
    }
    let cstr = unsafe { CStr::from_ptr(sidecar_prefix) };
    let s = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => {
            set_last_error("prmi_open: prefix is not valid UTF-8");
            unsafe { *out_handle = std::ptr::null_mut() };
            return -2;
        }
    };
    match LearnedIndex::open(Path::new(s)) {
        Ok(idx) => {
            unsafe { *out_handle = Handle(idx).into_raw() };
            0
        }
        Err(e) => {
            set_last_error(&format!("{e}"));
            unsafe { *out_handle = std::ptr::null_mut() };
            -3
        }
    }
}

/// Release all resources held by the handle. Safe to call with NULL.
///
/// # Safety
/// `handle` must be NULL or have been returned by `prmi_open` and not yet
/// closed.
#[no_mangle]
pub unsafe extern "C" fn prmi_close(handle: *mut prmi_index_t) {
    if handle.is_null() {
        return;
    }
    drop(unsafe { Handle::from_raw(handle) });
}

/// Thread-local last-error string. Valid until the next prmi_* call on
/// the same thread. Never returns NULL — empty string if no error.
#[no_mangle]
pub extern "C" fn prmi_last_error_message() -> *const c_char {
    with_last_error(|c| c.as_ptr())
}
